<a href="https://colab.research.google.com/github/deepaksuthar18/pytorch_understand/blob/main/tensor_pytroch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.9.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("GPU available!")
  print(f"use gpu:{torch.cuda.get_device_name(0)}")
else:
  print("GPU not available")


GPU available!
use gpu:Tesla T4


# Create a tensor

In [ ]:
# tensor empty

ten = torch.empty(2,3)  # empty function allocate the memory and crete a space in memory


In [ ]:
print(ten)

tensor([[6.0133e+02, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 1.1210e-43, 0.0000e+00]])


In [ ]:
type (ten)

torch.Tensor

In [ ]:
# using zero

torch.zeros(2,3)  # all value initialize from zero

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#  random value
torch.rand(2,3) # assing a rendom value

tensor([[0.7450, 0.0995, 0.2394],
        [0.1836, 0.2363, 0.6936]])

In [ ]:
torch.rand(2,3)

tensor([[0.0111, 0.8724, 0.9770],
        [0.4666, 0.5051, 0.8473]])

In [ ]:
# use seed

torch.manual_seed(100)   # we want each time random output same . so we will define manual_seed . so we run every time no change in tensor . it will same as it is . no changes
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# tensor

torch.tensor([[1,2,3,4],[5,6,7,8],[10,8,0,85]])  # we create a our custom tensor

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [10,  8,  0, 85]])

In [ ]:
#arange

print("using arange ---->", torch.arange(0,20,)) # define range. 0-20 is range (start-end)

using arange ----> tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])


In [ ]:
print("using arange ---->", torch.arange(0,20,2)) # define range. 0-20 is range . 2 is jump two time  (Start-end_step)

using arange ----> tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


In [ ]:
# linspace (linearly-space)

print("linspace ---->", torch.linspace(0,10,10)) #  torch.linspace() in PyTorch creates a one-dimensional tensor of evenly spaced values between a specified start and end point

linspace ----> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [ ]:
# eye

print("Eye ----> ", torch.eye(5))  # torch.eye in PyTorch is a function used to create a 2D tensor (matrix) with ones on the main diagonal and zeros elsewhere, known as an identity matrix

Eye ---->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
# full

print("full ---> ", torch.full((4,4), 6)) # we create 4x4 matrix  and this matrix each item is 6 is define

full --->  tensor([[6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6]])


# Tensor shape

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)     # copy of x variable but value changed

tensor([[1177435536, 1178912256,          0],
        [         0,          0,          0]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Data type

Here are some of the 'boxes' PyTorch uses to store different kinds of numbers:

| What kind of number?       | PyTorch's 'Box' Name | What does it mean?                                  |
|:---------------------------|:---------------------|:----------------------------------------------------|
| Numbers with tiny bits      | `torch.float16`      | For numbers that are not super big or super small, like 1.5, and don't need super-duper accuracy.  |
| Regular numbers with bits   | `torch.float32`      | Our usual numbers, like 3.14 or 10.5. Most common!  |
| Super accurate numbers      | `torch.float64`      | For numbers that need to be *very* precise, like when scientists count stars! |
| Whole numbers (small)       | `torch.int8`         | For whole numbers that are not too big, like 5 or -2. |
| Whole numbers (medium)      | `torch.int16`        | For whole numbers that are a bit bigger, like 100 or -50. |
| Whole numbers (big)         | `torch.int32`        | For bigger whole numbers, like 1000 or -500.        |
| Whole numbers (super big)   | `torch.int64`        | For really, really big whole numbers, like 1,000,000! |
| Yes or No answers           | `torch.bool`         | For things that are either True (yes!) or False (no!). |

Each 'box' is good for different things, just like you use different toy boxes for different toys!

### Adding Numbers (Addition ➕)
Imagine you have 2 apples and your friend gives you 3 more apples. How many do you have? You add them! PyTorch can do the same with its 'number boxes' (tensors).

In [ ]:
# Let's make our first box of numbers
box_a = torch.tensor([2, 5]) # This box has 2 and 5
print(f"First box (box_a): {box_a}")


# Let's make our second box of numbers
box_b = torch.tensor([3, 4]) # This box has 3 and 4
print(f"Second box (box_b): {box_b}")


# Now, let's add them together!

# PyTorch adds the first numbers, then the second numbers, and so on.
result_add = box_a + box_b
print(f"After adding (result_add): {result_add}")


# You can also use torch.add()
result_add_func = torch.add(box_a, box_b)
print(f"Using torch.add() (result_add_func): {result_add_func}")

First box (box_a): tensor([2, 5])
Second box (box_b): tensor([3, 4])
After adding (result_add): tensor([5, 9])
Using torch.add() (result_add_func): tensor([5, 9])


First, let's make our special box of numbers. Imagine these are how many candies your friends have.

In [ ]:
import torch
import collections # We'll need this for 'mode' later

# This is our box of numbers (tensor)!
# Your friends have 1, 5, 2, 8, 5, and 3 candies.
data_box = torch.tensor([1, 5, 2, 8, 5, 3], dtype=torch.float32) # Using float32 so division works nicely
print(f"Our box of numbers: {data_box}")

Our box of numbers: tensor([1., 5., 2., 8., 5., 3.])


### Mean (Average 🧑‍⚖️)
Imagine you want to share all the candies equally among your friends. How many candies would each friend get? That's the **mean** or **average**!

In [ ]:
# To find the average, PyTorch adds all the numbers and then divides by how many numbers there are.
# (1 + 5 + 2 + 8 + 5 + 3) / 6 = 24 / 6 = 4
mean_value = torch.mean(data_box)
print(f"The average number of candies (Mean): {mean_value}")

The average number of candies (Mean): 4.0


### Median (Middle Number ↔️)
If you line up all your friends from the one with the fewest candies to the one with the most, who would be in the very middle? That's the **median**!

In [ ]:
# First, PyTorch puts all the numbers in order: [1, 2, 3, 5, 5, 8]
# Then it finds the number(s) in the middle. If there are two, it takes the average of them.
# In our case, the middle numbers are 3 and 5. (3 + 5) / 2 = 4
median_value = torch.median(data_box) # torch.median returns the value and its index
print(f"The middle number of candies (Median): {median_value}")

The middle number of candies (Median): 3.0


### Standard Deviation (How Spread Out 📏)
This tells us how far apart the numbers in our box usually are from the average. If the numbers are all close to the average, this number is small. If they are very far apart, this number is big!

In [ ]:
# PyTorch calculates how much each number is different from the average.
# Then it does some special math (squaring, averaging, and taking a square root) to get one number.
# A small number here means most candies are close to the average of 4.
std_dev_value = torch.std(data_box)
print(f"How spread out the candies are (Standard Deviation): {std_dev_value}")

How spread out the candies are (Standard Deviation): 2.5298221111297607


### Variance (Super Spread Out 📐)
Variance is like a cousin to standard deviation. It also tells us how spread out the numbers are, but before we take the square root. It's often used by grown-ups in math!

In [ ]:
# Variance is the standard deviation squared. So, it's another way to measure spread.
# (It's like the 'before square root' step of standard deviation's special math.)
variance_value = torch.var(data_box)
print(f"Another way to see how spread out the candies are (Variance): {variance_value}")

Another way to see how spread out the candies are (Variance): 6.400000095367432


### Minimum (Smallest Number 👇)
Which friend has the fewest candies? That's the **minimum**!

In [ ]:
# PyTorch simply looks at all the numbers and finds the smallest one.
min_value = torch.min(data_box)
print(f"The smallest number of candies (Min): {min_value}")

The smallest number of candies (Min): 1.0


### Maximum (Biggest Number 👆)
Which friend has the most candies? That's the **maximum**!

In [ ]:
# PyTorch looks at all the numbers and finds the biggest one.
max_value = torch.max(data_box)
print(f"The biggest number of candies (Max): {max_value}")

The biggest number of candies (Max): 8.0


### Mode (Most Popular Number ✨)
Which number of candies appears most often in our box? That's the **mode**! Sometimes, there can be more than one mode if two numbers appear the same highest number of times.

In [ ]:
# PyTorch doesn't have a super simple 'mode' button for all types of boxes,
# but we can count how many times each number appears to find the most popular one.
# Our numbers are: [1, 5, 2, 8, 5, 3]
# 1 appears 1 time
# 2 appears 1 time
# 3 appears 1 time
# 5 appears 2 times (This is the most!)
# 8 appears 1 time

# We convert to a Python list to use a tool that counts for us easily
data_list = data_box.tolist()
counts = collections.Counter(data_list)

# Find the number that appears the most
# if there's a tie, it will show one of them.
mode_value = counts.most_common(1)[0][0]
print(f"The most popular number of candies (Mode): {mode_value}")

The most popular number of candies (Mode): 5.0


### Taking Numbers Away (Subtraction ➖)
If you have 5 cookies and eat 2, how many are left? You take them away (subtract)! PyTorch can do this too.

In [ ]:
import torch

# Let's start with a box of 5 and 10
box_c = torch.tensor([5, 10])
print(f"Starting box (box_c): {box_c}")

# And another box of 2 and 3 to take away
box_d = torch.tensor([2, 3])
print(f"Box to take away (box_d): {box_d}")

# Let's subtract!
# PyTorch takes away the first number from the first, and the second from the second.
result_sub = box_c - box_d
print(f"After taking away (result_sub): {result_sub}")

# You can also use torch.sub()
result_sub_func = torch.sub(box_c, box_d)
print(f"Using torch.sub() (result_sub_func): {result_sub_func}")

Starting box (box_c): tensor([ 5, 10])
Box to take away (box_d): tensor([2, 3])
After taking away (result_sub): tensor([3, 7])
Using torch.sub() (result_sub_func): tensor([3, 7])


### Multiplying Numbers (Multiplication ✖️)
If you have 2 groups of 3 toys, how many toys in total? You multiply! PyTorch knows how to multiply numbers in its boxes.

In [ ]:
import torch

# A box with 2 and 5
box_e = torch.tensor([2, 5])
print(f"First box (box_e): {box_e}")

# Another box with 3 and 2
box_f = torch.tensor([3, 2])
print(f"Second box (box_f): {box_f}")

# Let's multiply!
# PyTorch multiplies the first number by the first, and the second by the second.
result_mul = box_e * box_f
print(f"After multiplying (result_mul): {result_mul}")

# You can also use torch.mul()
result_mul_func = torch.mul(box_e, box_f)
print(f"Using torch.mul() (result_mul_func): {result_mul_func}")

First box (box_e): tensor([2, 5])
Second box (box_f): tensor([3, 2])
After multiplying (result_mul): tensor([ 6, 10])
Using torch.mul() (result_mul_func): tensor([ 6, 10])


### Sharing Numbers (Division ➗)
If you have 10 candies and you share them equally with 2 friends, how many candies does each friend get? You divide! PyTorch helps you share numbers too.

In [ ]:
import torch

# A box with 10 and 15
box_g = torch.tensor([10., 15.]) # We add '.' to make them float numbers for proper division
print(f"Starting box (box_g): {box_g}")

# Another box to divide by, with 2 and 3
box_h = torch.tensor([2., 3.])
print(f"Box to divide by (box_h): {box_h}")

# Let's divide!
# PyTorch divides the first number by the first, and the second by the second.
result_div = box_g / box_h
print(f"After dividing (result_div): {result_div}")

# You can also use torch.div()
result_div_func = torch.div(box_g, box_h)
print(f"Using torch.div() (result_div_func): {result_div_func}")

Starting box (box_g): tensor([10., 15.])
Box to divide by (box_h): tensor([2., 3.])
After dividing (result_div): tensor([5., 5.])
Using torch.div() (result_div_func): tensor([5., 5.])


# tensor opration on GPU


In [ ]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  device = torch.device("cpu")
  print("Using CPU")

# Create two tensors on the chosen device
tensor_a = torch.tensor([1.0, 2.0, 3.0], device=device)
tensor_b = torch.tensor([4.0, 5.0, 6.0], device=device)

# Perform an addition operation on the GPU
result_gpu = tensor_a + tensor_b

print(f"Tensor A on {device}: {tensor_a}")
print(f"Tensor B on {device}: {tensor_b}")
print(f"Result of A + B on {device}: {result_gpu}")

Using GPU: Tesla T4
Tensor A on cuda: tensor([1., 2., 3.], device='cuda:0')
Tensor B on cuda: tensor([4., 5., 6.], device='cuda:0')
Result of A + B on cuda: tensor([5., 7., 9.], device='cuda:0')


# Run time comparison CPU v/s GPU

In [ ]:
import torch
import time

matrix_size = 10000  # 10k martix size

# Create two random matrices
matrix_a = torch.randn(matrix_size, matrix_size)
matrix_b = torch.randn(matrix_size, matrix_size)

print(f"Performing matrix multiplication for {matrix_size}x{matrix_size} matrices...")

# --- CPU Computation ---
start_time_cpu = time.time()
result_cpu = torch.matmul(matrix_a, matrix_b)
end_time_cpu = time.time()
cpu_time = end_time_cpu - start_time_cpu
print(f"CPU computation time: {cpu_time:.4f} seconds")

# --- GPU Computation (if available) ---
if torch.cuda.is_available():
  device = torch.device("cuda")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")

  # Move matrices to GPU
  matrix_a_gpu = matrix_a.to(device)
  matrix_b_gpu = matrix_b.to(device)

  # Perform multiplication on GPU
  start_time_gpu = time.time()
  result_gpu = torch.matmul(matrix_a_gpu, matrix_b_gpu)
  end_time_gpu = time.time()
  gpu_time = end_time_gpu - start_time_gpu
  print(f"GPU computation time: {gpu_time:.4f} seconds")

  # Verify results (optional: move GPU result back to CPU for comparison)
  # assert torch.allclose(result_cpu, result_gpu.cpu(), atol=1e-3)
  # print("Results are approximately equal.")

else:
  print("GPU not available. Cannot perform GPU computation.")

Performing matrix multiplication for 10000x10000 matrices...
CPU computation time: 25.3146 seconds
Using GPU: Tesla T4
GPU computation time: 0.0005 seconds
